services:
  rankmate-user:
    build: .
    container_name: rankmate_user
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - public-network
      - private-network


networks:
  public-network:
     external: true
     name: ${PUBLIC_NETWORK_NAME}
  private-network:
     external: true
     name: ${PRIVATE_NETWORK_NAME}
